### ISSUE TITLE
Event lottery template crashing tool

### ISSUE THREAD

**Issue by lllKXlll** [Amarfas/FateGrandFarm#17]
Just a problem I ran into when trying the tool, if you put a template from the Event List folder on the Event Farm folder the program fails to run properly.

So just don't paste the unnumbered .csv files, and it should be fine. 
Maybe a warning would help avoid this confusion?

Templates examples are:
-Grand Nero Fest -D- - Event Quest
-Christmas 2023 -D- - Event Quest
-Battle in NY 2024 -D- - Event Quest

**Comment by Amarfas** [comment]
Should be fixed in release v1.1.0.
